create schema if not exists academico;
create schema if not exists ayudantia;
create schema if not exists convocatoria;
create schema if not exists notificacion;
create schema if not exists postulacion;
create schema if not exists seguridad;

create table if not exists academico.facultad
(
    id_facultad integer generated always as identity
        primary key,
    nombre_facultad varchar(150) not null,
    activo boolean
);

create table if not exists academico.carrera
(
    id_carrera integer generated always as identity
        primary key,
    id_facultad integer not null
        references facultad,
    nombre_carrera varchar(150) not null,
    activo boolean
);

create table if not exists academico.asignatura
(
    id_asignatura integer generated always as identity
        primary key,
    id_carrera integer not null
        references carrera,
    nombre_asignatura varchar(150) not null,
    semestre integer not null,
    activo boolean
);

create table if not exists academico.periodo_academico
(
    id_periodo_academico integer generated always as identity
        primary key,
    nombre_periodo varchar(100) not null,
    fecha_inicio date not null,
    fecha_fin date not null,
    estado varchar(30) not null,
    activo boolean
);

create table if not exists academico.estudiante
(
    id_estudiante integer generated always as identity
        primary key,
    id_usuario integer not null
        references seguridad.usuario,
    id_carrera integer not null
        references carrera,
    matricula varchar(30) not null
        unique,
    semestre integer not null,
    estado_academico varchar(30)
);

create table if not exists academico.docente
(
    id_docente integer generated always as identity
        primary key,
    id_usuario integer not null
        references seguridad.usuario,
    fecha_inicio date,
    fecha_fin date,
    activo boolean
);

create table if not exists academico.docente_asignatura
(
    id_docente_asignatura integer generated always as identity
        primary key,
    id_docente integer not null
        references docente,
    id_asignatura integer not null
        references asignatura,
    activo boolean
);

create table if not exists academico.coordinador
(
    id_coordinador integer generated always as identity
        primary key,
    id_usuario integer not null
        references seguridad.usuario,
    id_carrera integer not null
        references carrera,
    fecha_inicio date,
    fecha_fin date,
    activo boolean
);

create table if not exists academico.decano
(
    id_decano integer generated always as identity
        primary key,
    id_usuario integer not null
        references seguridad.usuario,
    id_facultad integer not null
        references facultad,
    fecha_inicio_gestion date,
    fecha_fin_gestion date,
    activo boolean
);

create table if not exists academico.ayudante_catedra
(
    id_ayudante_catedra integer generated by default as identity
        primary key,
    horas_ayudante numeric(5,2),
    id_usuario integer
        constraint fkbu2mhu5x8oh65cujfyox6o8f8
            references seguridad.usuario
);



create sequence tipo_estado_evidencia_ayudant_id_tipo_estado_evidencia_ayud_seq;

create sequence evidencia_registro_actividad_id_evidencia_registro_activida_seq;

create sequence tipo_sancion_ayudante_catedra_id_tipo_sancion_ayudante_cate_seq;

create table if not exists tipo_estado_evidencia_ayudantia
(
    id_tipo_estado_evidencia_ayudantia integer generated always as identity
        primary key,
    nombre_estado varchar(50),
    descripcion text,
    activo boolean
);

alter sequence tipo_estado_evidencia_ayudant_id_tipo_estado_evidencia_ayud_seq owned by tipo_estado_evidencia_ayudantia.id_tipo_estado_evidencia_ayudantia;

create table if not exists ayudantia
(
    id_ayudantia integer generated always as identity
        primary key,
    id_tipo_estado_evidencia_ayudantia integer not null
        references tipo_estado_evidencia_ayudantia,
    id_postulacion integer not null
        constraint fktenwg9alao08j40w2y1pcyjqc
            references postulacion.postulacion,
    fecha_inicio date,
    fecha_fin date,
    horas_cumplidas integer
);

create table if not exists registro_actividad
(
    id_registro_actividad integer generated always as identity
        primary key,
    id_ayudantia integer not null
        references ayudantia,
    descripcion_actividad text,
    tema_tratado text,
    fecha date,
    numero_asistentes integer,
    horas_dedicadas numeric(5,2),
    estado_revision varchar(30)
);

create table if not exists evidencia_registro_actividad
(
    id_evidencia_registro_actividad integer generated always as identity
        primary key,
    id_registro_actividad integer not null
        references registro_actividad,
    tipo_evidencia varchar(50),
    archivo bytea,
    nombre_archivo varchar(150),
    fecha_subida date,
    activo boolean
);

alter sequence evidencia_registro_actividad_id_evidencia_registro_activida_seq owned by evidencia_registro_actividad.id_evidencia_registro_actividad;

create table if not exists certificado
(
    id_certificado integer generated always as identity
        primary key,
    id_ayudantia integer not null
        references ayudantia,
    id_usuario integer
        references seguridad.usuario,
    codigo_verificacion varchar(50),
    fecha_emision date,
    total_horas_certificadas integer,
    archivo bytea,
    estado varchar(30),
    activo boolean
);

create table if not exists ayudante_catedra
(
    id_ayudante_catedra integer generated always as identity
        primary key,
    id_usuario integer
        references seguridad.usuario,
    horas_ayudante numeric(5,2)
);

create table if not exists tipo_sancion_ayudante_catedra
(
    id_tipo_sancion_ayudante_catedra integer generated always as identity
        primary key,
    nombre_tipo_sancion varchar(100),
    activo boolean
);

alter sequence tipo_sancion_ayudante_catedra_id_tipo_sancion_ayudante_cate_seq owned by tipo_sancion_ayudante_catedra.id_tipo_sancion_ayudante_catedra;

create table if not exists sancion_ayudante_catedra
(
    id_sancion_ayudante_catedra integer generated always as identity
        primary key,
    id_tipo_sancion_ayudante_catedra integer
        references tipo_sancion_ayudante_catedra,
    id_ayudante_catedra integer
        references ayudante_catedra,
    fecha_sancion date,
    activo boolean,
    motivo varchar(150)
);



